services:
  api:
    image: ghcr.io/${GITHUB_REPOSITORY}:test
    container_name: qoo-quote-api
    expose:
      - 3005 
    env_file:
      - .env.test
    networks:
      - qq-test-internal
      - traefik-public
    restart: always
    depends_on:
      database:
        condition: service_healthy
    labels:
      - 'traefik.enable=true'
      - 'traefik.docker.network=traefik-public'
      - 'traefik.http.services.qoo-quote-api.loadbalancer.server.port=3005'
      - 'traefik.http.routers.qoo-quote-api.rule=Host(`qq-api-test-v0.homelab-kaleici.space`)'
      - 'traefik.http.routers.qoo-quote-api.entrypoints=websecure'
      - 'traefik.http.routers.qoo-quote-api.service=qoo-quote-api'
      - 'traefik.http.routers.qoo-quote-api.tls=true'
      - 'traefik.http.routers.qoo-quote-api.tls.certresolver=cloudflare'
      - 'traefik.http.middlewares.qoo-quote-api-headers.headers.sslredirect=true'
      - 'traefik.http.routers.qoo-quote-api.middlewares=qoo-quote-api-headers'

  database:
    image: postgres:13-alpine
    container_name: qoo-quote-database
    env_file:
      - .env.test
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - '5433:5432'
    volumes:
      - qoo-quote-database:/var/lib/postgresql/data
    networks:
      - qq-test-internal
    restart: always
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  qoo-quote-database:
    name: qoo-quote-database

networks:
  traefik-public:
    external: true
    name: traefik-public
  qq-test-internal:
    name: qq-test-internal
    driver: bridge
