services:
  api:
    image: qoo-quote-api:latest
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: qoo-quote-api
    expose:
      - 3005
    env_file:
      - .env.test
    networks:
      - qoo-quote-network
    command: >
      sh -c "
        echo 'Waiting for database...' &&
        while ! nc -z database 5432; do sleep 1; done &&
        echo 'Database is ready!' &&
        npm run start:dev
      "
    volumes:
      - .:/app
    restart: always
    depends_on:
      database:
        condition: service_healthy
    labels:
      traefik.enable: 'true'
      traefik.http.routers.qoo-quote.rule: 'Host(`qq-api-v0.homelab-kaleici.space`)'
      traefik.http.routers.qoo-quote.entrypoints: 'websecure'
      traefik.http.services.qoo-quote.loadbalancer.server.port: '3005'
      traefik.http.routers.qoo-quote.tls: 'true'
      traefik.http.routers.qoo-quote.tls.certresolver: 'cloudflare'
      traefik.http.middlewares.qoo-quote-headers.headers.sslredirect: 'true'

  database:
    image: postgres:13-alpine
    container_name: qoo-quote-database
    env_file:
      - .env.development
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - '5433:5432'
    volumes:
      - qoo-quote-database:/var/lib/postgresql/data
    networks:
      - qoo-quote-network
    restart: always
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  qoo-quote-database:
    name: qoo-quote-database

networks:
  qoo-quote-network:
    name: qoo-quote-network
    external: true
