FROM node:22-alpine
WORKDIR /app

# Install pnpm
RUN npm install -g pnpm

# Install nest CLI globally
RUN npm install -g @nestjs/cli

# Copy package files
COPY pnpm-lock.yaml package.json ./

# Install dependencies including dev dependencies since we need them for build
RUN pnpm install

COPY . .

# Build the application
RUN pnpm run build

# Remove dev dependencies for production
RUN pnpm prune --prod

CMD ["pnpm", "start:prod"] 