name: Deploy to Test Environment

on:
  push:
    branches:
      - test

permissions:
  contents: read
  packages: write
  actions: read

jobs:
  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    environment: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Validate Secrets
        run: |
          if [ -z "${{ secrets.DOT_ENV_TEST }}" ]; then echo "DOT_ENV_TEST is not set!" >&2; exit 1; fi
          if [ -z "${{ secrets.SSH_KEY }}" ]; then echo "SSH_KEY is not set!" >&2; exit 1; fi
          if [ -z "${{ secrets.SSH_IP }}" ]; then echo "SSH_IP is not set!" >&2; exit 1; fi
          if [ -z "${{ secrets.SSH_USER }}" ]; then echo "SSH_USER is not set!" >&2; exit 1; fi

      - name: Create .env.test file
        run: |
          umask 077
          echo "${{ secrets.DOT_ENV_TEST }}" > .env.test

      - name: Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.test
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:test
            ghcr.io/${{ github.repository }}:test-${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            NODE_ENV=test

  deploy:
    name: Deploy to Test Environment
    needs: build
    runs-on: ubuntu-latest
    environment: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup SSH Agent
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Deploy to Test Server
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_IP: ${{ secrets.SSH_IP }}
        run: |
          ssh -o StrictHostKeyChecking=no -tt $SSH_USER@$SSH_IP << 'EOF'
            set -e

            echo ">>> Navigating to test project directory"
            cd ~/qoo-quote-be || exit 1

            echo ">>> Pulling latest changes"
            git pull origin test

            echo ">>> Creating .env.test file"
            echo "${{ secrets.DOT_ENV_TEST }}" > .env.test

            echo ">>> Logging into GitHub Container Registry"
            echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

            # Build and start services
            echo ">>> Starting services"
            docker-compose -f compose.test.yml --env-file .env.test up -d

            echo ">>> Checking container status"
            docker-compose -f compose.test.yml ps

            echo ">>> Showing recent logs"
            docker-compose -f compose.test.yml logs --tail=50 
          EOF

      - name: Notify on Success
        if: success()
        run: |
          echo "Deployment to test environment completed successfully!"

      - name: Notify on Failure
        if: failure()
        run: |
          echo "Deployment to test environment failed!"
